services:

  user_api:
    container_name: user_api
    build:
      context: src/app
      dockerfile: ./Dockerfile
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8011
    ports:
      - 8011:8011
    env_file:
      - ./src/app/.env_user_api
    environment:
      - USE_AUTH=False

  # nginx_user_api:
  #   image: nginx:1.19.2
  #   container_name: nginx_user_api
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/configs:/etc/nginx/conf.d:ro
  #   depends_on:
  #     - user_api
  #   ports:
  #     - 8081:8081

  filebeat:
    container_name: user_data_filebeat
    image: elastic/filebeat:7.3.2
    command: filebeat -e -strict.perms=false
    volumes:
      - user_data_nginx:/var/log/nginx:ro
      - ./src/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - user_api
      # - nginx_user_api

  mongors1n1:
    container_name: mongors1n1
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_data1:/data/db

  mongors1n2:
    container_name: mongors1n2
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_data2:/data/db

  mongors1n3:
    container_name: mongors1n3
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_data3:/data/db

  mongors2n1:
    container_name: mongors2n1
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_data4:/data/db

  mongors2n2:
    container_name: mongors2n2
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_data5:/data/db

  mongors2n3:
    container_name: mongors2n3
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_data6:/data/db

  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_config1:/data/db

  mongocfg2:
    container_name: mongocfg2
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_config2:/data/db

  mongocfg3:
    container_name: mongocfg3
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_config3:/data/db

  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
      - mongors1n1
      - mongors1n2
      - mongors1n3
      - mongors2n1
      - mongors2n2
      - mongors2n3
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  user_data_nginx:
  ugc_mongo_cluster_data1:
  ugc_mongo_cluster_data2:
  ugc_mongo_cluster_data3:
  ugc_mongo_cluster_data4:
  ugc_mongo_cluster_data5:
  ugc_mongo_cluster_data6:
  ugc_mongo_cluster_config1:
  ugc_mongo_cluster_config2:
  ugc_mongo_cluster_config3:

networks:
 default:
   external:
     name: network
