version: '3'

services:
  api_ugc:
    container_name: api_ugc
    build: ./
    volumes:
      - ./src:/code
    ports:
      - '8000:8000'
    env_file:
      - .env_ugc
    restart: always
    networks:
      - default

  nginx_ugc:
    build: nginx
    container_name: nginx_ugc
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data:/data/
    depends_on:
      - api_ugc
    ports:
      - '80:80'
    networks:
      - default

  ugc_etl:
    build:
      context: .
      dockerfile: etl_ugc/Dockerfile
    container_name: ugc_etl
    depends_on:
      - api_ugc
    command: >
      python etl_ugc/app.py
    volumes:
      - ./etl_ugc:/code
    env_file:
      - etl_ugc/.env_etl_ugc
    networks:
      - default

  filebeat:
    container_name: ugc_filebeat
    image: elastic/filebeat:7.3.2
    command: filebeat -e -strict.perms=false
    volumes:
      - nginx_ugc:/var/log/nginx:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - api_ugc
      - nginx_ugc

volumes:
  nginx_ugc:

networks: 
  default: 
    external: 
      name: network